Practisequestion16/Models/AccountDto.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Practisequestion16.Models
{
    public class AccountDto
    {
        public int Id { get; set; }

        public string FirstName { get; set; }

        public string LastName { get; set; }
        public string Username { get; set; }

        public string Password { get; set; }
    }
}

Practisequestion16/Models/BrandDto.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Practisequestion16.Models
{
    public class BrandDto
    {
        public int Id { get; set; }

        public string BrandName { get; set; }
    }
}

Practisequestion16/Models/CategoryDto.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Practisequestion16.Models
{
    public class CategoryDto
    {
        public int Id { get; set; }

        public string CategoryName { get; set; }
    }
}

Practisequestion16/Models/ProductDto.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Practisequestion16.Models
{
    public class ProductDto
    {
        public int Id { get; set; }

        public string ProductName { get; set; }

        public int CategoryId { get; set; }

        public int BrandId { get; set; }

        public decimal Qty { get; set; }

        public decimal Price { get; set; }

        public string Image_Path { get; set; }

        public HttpPostedFileBase Image { get; set; }

        //public string IsActive { get; set; }
        //public List<string>  check { get; set; }
    }
}

Practisequestion16/Controllers/BrandController.cs
using Practisequestion16.Models;
using Practisequestion16.Service;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Practisequestion16.Controllers
{
    
    public class BrandController : Controller
    {
        BrandService brandService = new BrandService();
        // GET: Brand
        public ActionResult Brand(int  id = 0)
        {
            if (id > 0)
            {
                return View(brandService.GetById(id));
            }
            else
            {
                return View();
            }
        }
        [HttpPost]
        public ActionResult Brand(BrandDto brandDto)
        {
            if(brandDto.Id == 0)
            {
                brandService.AddBrand(brandDto);
            }
            else
            {
                brandService.UpdateBrand(brandDto);
            }
            return RedirectToAction("GetAllBrand");
        }
        
        [HttpGet]

        public ActionResult GetAllBrand()
        {
            var data = brandService.GetBrandList();
            return View(data);
        }
        [HttpGet]
        public ActionResult DeleteBrand(int id)
        {
            brandService.DeleteBrand(id);
            return RedirectToAction("GetAllBrand");
        }
    }
}

Practisequestion16/Controllers/CategoryController.cs
using Practisequestion16.Models;
using Practisequestion16.Service;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Practisequestion16.Controllers
{
    
    public class CategoryController : Controller
    {
        CategoryService categoryService = new CategoryService();
        // GET: Category
        public ActionResult Category(int id = 0)
        {
            if (id > 0)
            {
                return View(categoryService.GetById(id));
            }
            else

            { return View(); }
        }
        
            
        
        [HttpPost]
        public ActionResult Category(CategoryDto categoryDto)
        {
            if (categoryDto.Id == 0)
            {
                categoryService.AddCategory(categoryDto);
            }
            else
            {
                categoryService.UpdateCategory(categoryDto);
            }
            
            return RedirectToAction("GetAllCategory");
        }
        
        [HttpGet]

        public ActionResult GetAllCategory()
        {
            var data = categoryService.GetCategoryList();
            return View(data);
        }
        [HttpGet]
        public ActionResult DeleteCategory(int id)
        {
            categoryService.DeleteCategory(id);
            return RedirectToAction("GetAllCategory");
        }
    }
}

Practisequestion16/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Practisequestion16.Controllers
{

    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Practisequestion16/Controllers/LoginController.cs
using Practisequestion16.Models;
using Practisequestion16.Service;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Practisequestion16.Controllers
{
    public class LoginController : Controller
    {
        AccountServices accountServices = new AccountServices();
        // GET: Account
        
        public ActionResult Login()
        
        {
            return View();
        }
        [HttpPost]

        public ActionResult Login(AccountDto accountDto)
        {
            if (accountServices.Login(accountDto.Username, accountDto.Password))
            {
                return RedirectToAction("GetAllProducts", "Product",null);
            }
            
            return View();
        }

        public ActionResult Signup()
        {
            return View();
        }
        [HttpPost]

        public ActionResult Signup(AccountDto accountDto)
        {
            accountServices.AddUser(accountDto);
            return View();
        }

        [HttpGet]

        public ActionResult GetAllUsers()
        {
            var data = accountServices.GetAllUsers();
            return View(data);
        }



    }
}

Practisequestion16/Controllers/ProductController.cs
using Practisequestion16.Models;
using Practisequestion16.Service;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Practisequestion16.Controllers
{
    
    public class ProductController : Controller
    {
        ProductService productService = new ProductService();
        CategoryService categoryService = new CategoryService();
        BrandService brandService = new BrandService();
        // GET: Product
        public ActionResult Product(int id = 0)
        {
            ViewBag.CateDrp = categoryService.GetCategoryListItem();
            ViewBag.BrandDrp = brandService.GetSelectListItems();
            if (id > 0)
            {
              
                return View(productService.GetById(id));
            }
            else
            {
                return View();
            }
        }
        
        [HttpPost]
        public ActionResult Product(ProductDto productDto)
        {
            if (productDto.Image.ContentLength > 0)
            {
                var fileName = Path.GetFileName(productDto.Image.FileName);
                var imageLocation = Path.Combine(Server.MapPath("~/App_Data/Pictures"), fileName);
                productDto.Image.SaveAs(imageLocation);
                productDto.Image_Path = imageLocation;
            }
            ViewBag.CateDrp = categoryService.GetCategoryListItem();
            ViewBag.BrandDrp = brandService.GetSelectListItems();
            productService.AddProduct(productDto);
            return View();

        }

        [HttpGet]
        public ActionResult GetAllProducts()
        {
            var data = productService.GetAllProducts();
            ViewBag.CateDrp = categoryService.GetCategoryListItem();
            ViewBag.BrandDrp = brandService.GetSelectListItems();
            return View(data);
        }
        [HttpGet]
        public ActionResult DeleteProduct(int id)
        {
            productService.DeleteProduct(id);
            return RedirectToAction("GetAllProducts");
        }
    }
}

Practisequestion16/Views/Brand/Brand.cshtml
@model Practisequestion16.Models.BrandDto
@{
    ViewBag.Title = "Brand";
}

<h2>Brand</h2>

@using (Html.BeginForm())
{
    @*<label>BrandId</label>
    @Html.TextBoxFor(X => X.Id)*@
    <br />
    <label>BrandName</label>
    @Html.TextBoxFor(X => X.BrandName)
    <br />
    <button type="submit">Submit</button>
}

Practisequestion16/Views/Brand/GetAllBrand.cshtml
@model List<Practisequestion16.Models.BrandDto>
@{
    ViewBag.Title = "Brand";
}

<h2>GetAllBrand</h2>

@Html.ActionLink("Add new ", "Brand", null, new { @class = "btn btn-primary" })


<table class=" table table-bordered">

    <tr>
        <td>
            BrandId
        </td>
        <td>
            BrandName
        </td>
    </tr>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @item.Id
                </td>
                <td>
                    @item.BrandName
                </td>
                <td>
                    @Html.ActionLink("Edit", "Brand", new { id = item.Id }) | @Html.ActionLink("Delete", "DeleteBrand", new { id = item.Id })
                </td>

            </tr>

        }
    </tbody>
</table>

Practisequestion16/Views/Category/Category.cshtml
@model Practisequestion16.Models.CategoryDto
@{
    ViewBag.Title = "Category";
}

<h2>Category</h2>

@using (Html.BeginForm())
{
    @*<label>Id</label>
    @Html.TextBoxFor(x => x.Id)*@
    <br />
    <label>CategoryName</label>
    @Html.TextBoxFor(x => x.CategoryName)
    <br />
    <button type="submit">Submit</button>
}

Practisequestion16/Views/Category/GetAllCategory.cshtml
@model List<Practisequestion16.Models.CategoryDto>
@{
    ViewBag.Title = "Category";
}

<h2>GetAllCategory</h2>

@Html.ActionLink("Add new ", "Category", null, new { @class = "btn btn-primary" })



<table class=" table table-bordered">

    <tr>
        <td>
            CategoryId
        </td>
        <td>
            CategoryName
        </td>
    </tr>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @item.Id
                </td>
                <td>
                    @item.CategoryName
                </td>
                <td>
                    @Html.ActionLink("Edit", "Category", new { id = item.Id }) |
                    @Html.ActionLink("Delete", "DeleteCategory", new { id = item.Id })
                </td>
                
            </tr>

        }
    </tbody>
</table>

Practisequestion16/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<main aria-labelledby="title">
    <h2 id="title">@ViewBag.Title.</h2>
    <h3>@ViewBag.Message</h3>

    <p>Use this area to provide additional information.</p>
</main>

Practisequestion16/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<main aria-labelledby="title">
    <h2 id="title">@ViewBag.Title.</h2>
    <h3>@ViewBag.Message</h3>

    <address>
        One Microsoft Way<br />
        Redmond, WA 98052-6399<br />
        <abbr title="Phone">P:</abbr>
        425.555.0100
    </address>

    <address>
        <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
        <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
    </address>
</main>

Practisequestion16/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<main>
    <section class="row" aria-labelledby="aspnetTitle">
        <h1 id="title">ASP.NET</h1>
        <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
        <p><a href="https://asp.net" class="btn btn-primary btn-md">Learn more &raquo;</a></p>
    </section>

    <div class="row">
        <section class="col-md-4" aria-labelledby="gettingStartedTitle">
            <h2 id="gettingStartedTitle">Getting started</h2>
            <p>
                ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
                enables a clean separation of concerns and gives you full control over markup
                for enjoyable, agile development.
            </p>
            <p><a class="btn btn-outline-dark" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
        </section>
        <section class="col-md-4" aria-labelledby="librariesTitle">
            <h2 id="librariesTitle">Get more libraries</h2>
            <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
            <p><a class="btn btn-outline-dark" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
        </section>
        <section class="col-md-4" aria-labelledby="hostingTitle">
            <h2 id="hostingTitle">Web Hosting</h2>
            <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
            <p><a class="btn btn-outline-dark" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
        </section>
    </div>
</main>

Practisequestion16/Views/Login/Login.cshtml
@model Practisequestion16.Models.AccountDto
@{
    ViewBag.Title = "login";
    Layout = null;
}

<h2>login</h2>

@using (Html.BeginForm())
{
    @*<label>
        FirstName
    </label>
    @Html.TextBoxFor(x => x.FirstName)<br />
    <label>LastName</label>
    @Html.TextBoxFor(x => x.LastName)<br />*@
    <label>UserName</label>
    @Html.TextBoxFor(x => x.Username)<br />
    <br />
    <label>Password</label>
    @*@Html.TextBoxFor(x => x.Password)<br />*@
    <br />
    @Html.PasswordFor(X => X.Password)<br />
    <button type="submit">Login</button><br />
    @*<button type="reset">Reset</button><br />*@
    <br />
    <div>
        @Html.ActionLink("Click to sign", "Signup")
    </div>

}

Practisequestion16/Views/Login/Signup.cshtml
@model Practisequestion16.Models.AccountDto
@{
    ViewBag.Title = "Signup";
}

<h2>Signup</h2>

@using (Html.BeginForm())
{
    <label>
        FirstName
    </label>
    @Html.TextBoxFor(x => x.FirstName)
    <br />
    <label>LastName</label>
    @Html.TextBoxFor(x => x.LastName)
    <br />
    <label>UserName</label>
    @Html.TextBoxFor(x => x.Username)
    <br />
    <label>Password</label>
    @Html.TextBoxFor(x => x.Password)
    <br />
    <button type="submit">Submit</button>
    <br />
    <button type="reset">Reset</button>
    <br />
    <br />
    <div>
        @Html.ActionLink("Click to Login", "Login")
    </div>

}

Practisequestion16/Views/Product/GetAllProducts.cshtml
@model List<Practisequestion16.Models.ProductDto>
@{
    ViewBag.Title = "Products";
}

<h2>GetAllProducts</h2>

@Html.ActionLink("Add new ", "Product", null, new { @class = "btn btn-primary" })

<table class=" table table-bordered">

        <tr>
                <td>ProductId</td>
                <td>ProductName</td>
                <td>CategoryId</td>
                <td>BrandId</td>
                <td>Qty</td>
                <td>Price</td>
        </tr>
    

    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.Id</td>
                <td>@item.ProductName</td>
                <td>@item.CategoryId</td>
                <td>@item.BrandId</td>
                <td>@item.Qty</td>
                <td>@item.Price</td>
                <td><img src="@item.Image_Path" height="100" width="100" /></td>
                <td>
                    @Html.ActionLink("Edit", "Product", new { id = item.Id }) | 
                    @Html.ActionLink("Delete", "DeleteProduct", new { id = item.Id })
                </td>
                @*<td>
                    @Html.ActionLink("Edit", "Student", new { id = item.StdId })

                    @Html.ActionLink("Delete", "DeleteStudent", new { id = item.StdId })*@
                <!--</td>-->
            </tr>
        }   
    </tbody>
</table>

Practisequestion16/Views/Product/Product.cshtml
@model Practisequestion16.Models.ProductDto
@{
    ViewBag.Title = "Products";
}

<h2>Product</h2>
<br />
@Html.ActionLink("Add new ", "Product", null, new { @class = "btn btn-primary" })
<br />



@using (Html.BeginForm("Product","Product",FormMethod.Post, new { enctype = "multipart/form-data" }))
{

    @ViewBag.Title

    <br />
    <label>ProductName</label>
    @Html.TextBoxFor(X => X.ProductName)
    <br />
    <label>CategoryId</label>
    @Html.DropDownListFor(X => X.CategoryId, ViewBag.CateDrp as List<SelectListItem>)
    <br />
    <label>BrandId</label>
    @Html.DropDownListFor(X => X.BrandId, ViewBag.BrandDrp as List<SelectListItem>)
    <br />
    <label>Qty</label>
    @Html.TextBoxFor(X => X.Qty)
    <br />
    <label>Price</label>
    @Html.TextBoxFor(X => X.Price)
    <br />

    <br />
    <label>Image</label>

    <input type="file" name="Image" id="Image" />

    @*@Html.ActionLink("Edit", "Product", new { id = item.Id })
    <br />

    @Html.ActionLink("Delete", "DeleteStudent", new { id = item.Id })*@
    <br />

    @*<label>Is Active</label>
        @Html.RadioButtonFor(x => x.IsActive, "Yes") <label>Yes</label>
        @Html.RadioButtonFor(x => x.IsActive, "No")<label>No</label>
        <br />
        <label>Intreseted Topic</label>
        @Html.ListBoxFor(x => x.check, ViewBag.CateDrp as List<SelectListItem>) <label>Cricket</label>;*@

    <br />
    <button type="submit">Submit</button>
}

Practisequestion16/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark">
        <div class="container">
            @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" title="Toggle navigation" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li>@Html.ActionLink("Home", "Index", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Category", "GetAllCategory", "Category", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Brand", "GetAllBrand", "Brand", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Product", "GetAllProducts", "Product", new { area = "" }, new { @class = "nav-link" })</li>

                    <li>@Html.ActionLink("Login", "login", "Login", new { area = "" }, new { @class = "nav-link" })</li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>